minimumReleaseAge: 7200 # 5 days (in minutes)
minimumReleaseAgeExclude:
  - '@biomejs/biome'
  - '@biomejs/cli-darwin-arm64'
  - '@biomejs/cli-darwin-x64'
  - '@biomejs/cli-linux-arm64-musl'
  - '@biomejs/cli-linux-arm64'
  - '@biomejs/cli-linux-x64-musl'
  - '@biomejs/cli-linux-x64'
  - '@biomejs/cli-win32-arm64'
  - '@biomejs/cli-win32-x64'
  - brace-expansion@1.1.17 || 1.1.18 || 2.1.3 || 2.1.4 || 5.0.9

allowBuilds:
  cypress: true
  esbuild: true
  vue-demi: true

peerDependencyRules:
  allowedVersions:
    eslint: "10"

overrides:
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  glob@>=10.0.0 <12.0.0: ^13.0.0
  source-map@>=0.8.0-beta.0 <0.9.0: ^0.7.4
