allowBuilds:
  cypress: true
  esbuild: true
  vue-demi: true
minimumReleaseAge: 20160 # 2 weeks (in minutes)
minimumReleaseAgeExclude:
  - '@biomejs/biome'
  - '@biomejs/cli-darwin-arm64'
  - '@biomejs/cli-darwin-x64'
  - '@biomejs/cli-linux-arm64-musl'
  - '@biomejs/cli-linux-arm64'
  - '@biomejs/cli-linux-x64-musl'
  - '@biomejs/cli-linux-x64'
  - '@biomejs/cli-win32-arm64'
  - '@biomejs/cli-win32-x64'
  - qs@6.15.2
  - tmp@0.2.6
onlyBuiltDependencies:
  - cypress
  - esbuild
  - vue-demi
