allowBuilds:
  cypress: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - ws@8.20.1
  - uuid@11.1.1
  - js-cookie@3.0.6
  - qs@6.15.2
  - tmp@0.2.6
  - vitest@4.1.0
onlyBuiltDependencies:
  - cypress
  - esbuild
  - vue-demi
overrides:
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
