<script setup lang="ts">
// Start code generated by https://vue-echarts.dev/#codegen
import { LineChart } from 'echarts/charts'
import type { LineSeriesOption } from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent,
  MarkLineComponent
} from 'echarts/components'
import type {
  TitleComponentOption,
  TooltipComponentOption,
  LegendComponentOption,
  GridComponentOption,
  MarkLineComponentOption
} from 'echarts/components'
import type { ComposeOption } from 'echarts/core'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { ref, watch, computed } from 'vue'
import VChart from 'vue-echarts'

import { colorItems, colorSpeed } from '../colors'
import type { DataRowType } from '../types'

interface Props {
  data: DataRowType[]
  settings: { showDays: boolean; unitSpeed: string }
  ips?: number
  target: number
}

const props = withDefaults(defineProps<Props>(), {
  ips: 0
})

use([
  TitleComponent,
  TooltipComponent,
  LegendComponent,
  GridComponent,
  MarkLineComponent,
  LineChart,
  CanvasRenderer
])

type EChartsOption = ComposeOption<
  | TitleComponentOption
  | TooltipComponentOption
  | LegendComponentOption
  | GridComponentOption
  | MarkLineComponentOption
  | LineSeriesOption
>
// End generated code

const speedInverter = computed(() => (props.target > 0 ? 1 : -1))

const unitFactor = computed(() => {
  const unitSpeed = props.settings.unitSpeed as 'sec' | 'min' | 'hour' | 'day'
  return {
    sec: 1,
    min: 60,
    hour: 3600,
    day: 86400
  }[unitSpeed]
})

const option = ref<EChartsOption>({
  tooltip: {},
  legend: {},
  series: [
    {
      type: 'line',
      smooth: true,
      symbolSize: 10,
      silent: true,
      animation: false,
      yAxisIndex: 0,
      data: [],
      color: colorItems,
      areaStyle: { opacity: 0.5 }
    },
    {
      type: 'line',
      smooth: true,
      symbolSize: 10,
      silent: true,
      animation: false,
      yAxisIndex: 1,
      color: colorSpeed,
      data: [],
      markLine: {
        symbol: 'none',
        label: { show: false },
        silent: true,
        animation: true,
        data: [{ yAxis: 0 }]
      }
    }
  ],
  xAxis: {
    type: 'time',
    minInterval: 60000, // no seconds
    minorTick: { show: false }, // for mobile display
    splitNumber: 3
  },
  yAxis: [
    {
      name: 'Value',
      position: 'left',
      type: 'value',
      nameTextStyle: { color: colorItems },
      axisLabel: { color: colorItems }
    },
    {
      name: 'Speed',
      type: 'value',
      position: 'right',
      nameTextStyle: { color: colorSpeed },
      axisLabel: { color: colorSpeed },
      splitLine: { show: false } // no grid line,
    }
  ]
})

watch(
  [() => props.data, () => props.settings, () => props.ips],
  () => {
    updateChart()
  },
  { deep: true, immediate: true }
)

function updateChart() {
  const speedFactor = speedInverter.value * unitFactor.value

  option.value.series = option.value.series as LineSeriesOption[]
  if (option.value.series[0]) {
    option.value.series[0].data = props.data.map(row => [row.date, row.items])
  }
  if (option.value.series[1]) {
    option.value.series[1].data = props.data
      .slice(1)
      .map(row => [row.date, row.speed * speedFactor])
  }
  // update mean speed line
  if (option.value.series[1]?.markLine) {
    option.value.series[1].markLine.data = [{ yAxis: props.ips * speedFactor }]
  }
  if (props.data.length > 0) {
    option.value.yAxis = (option.value.yAxis || []) as [{}, {}]
  }
}
</script>

<template>
  <VChart
    class="chart"
    :option="option"
    autoresize
  />
</template>

<style scoped>
.chart {
  height: 400px;
}
</style>
